name: Go

on:
  push:
    branches: [ main ]
    tags:
      - v*.*

  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Clone 
      run: |
        git clone https://github.com/apache/beam --depth=1
        pushd beam/sdks/python/container

        git fetch --tags

        # Get latest tag name
        latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
        export latestTag

        # Checkout latest tag
        git checkout $latestTag
        echo "LATEST_TAG=$latestTag" >> $GITHUB_ENV

        go build -o python-boot -ldflags "-s -w" .
        

    - name: Release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTINUOUS_RELEASE_TAG: ${{ env.LATEST_TAG }}
          GITHUB_CONTINUOUS_RELEASE_NAME: ${{ env.LATEST_TAG }}
          GITHUB_CONTINUOUS_RELEASE_TYPE: stable
      run: |
        wget -q https://github.com/srevinsaju/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
        chmod +x pyuploadtool-x86_64.AppImage
        ./pyuploadtool-x86_64.AppImage beam/sdks/python/container/python-boot 


